artifact_location: /Users/jaa1090/Documents/RLClass/week-3-intro-to-marl-Jkaslam/submission/mlflow/0
creation_time: 1695824317242
experiment_id: '0'
last_update_time: 1695824317242
lifecycle_stage: active
name: Default
