artifact_uri: /Users/jaa1090/Documents/RLClass/week-3-intro-to-marl-Jkaslam/submission/mlflow/718926273277873901/be925d339e25412bb92001bf1bbed3ba/artifacts
end_time: null
entry_point_name: ''
experiment_id: '718926273277873901'
lifecycle_stage: active
run_id: be925d339e25412bb92001bf1bbed3ba
run_name: CentralizedCritic_MultiGrid-CompetativeRedBlueDoor-v3-CTDE-Red_e7e95_00000
run_uuid: be925d339e25412bb92001bf1bbed3ba
source_name: ''
source_type: 4
source_version: ''
start_time: 1695863898710
status: 1
tags: []
user_id: unknown
