artifact_uri: /Users/jaa1090/Documents/RLClass/week-3-intro-to-marl-Jkaslam/submission/mlflow/118076633174562951/16c5caf8fc9646baa2daefc703a03567/artifacts
end_time: null
entry_point_name: ''
experiment_id: '118076633174562951'
lifecycle_stage: active
run_id: 16c5caf8fc9646baa2daefc703a03567
run_name: CentralizedCritic_MultiGrid-CompetativeRedBlueDoor-v3-CTDE-Red_c0cb4_00000
run_uuid: 16c5caf8fc9646baa2daefc703a03567
source_name: ''
source_type: 4
source_version: ''
start_time: 1695862544598
status: 1
tags: []
user_id: unknown
