artifact_uri: /Users/jaa1090/Documents/RLClass/week-3-intro-to-marl-Jkaslam/submission/mlflow/959747692627863443/6b2c006b839b43cbaefb65f0ce8c6e1b/artifacts
end_time: null
entry_point_name: ''
experiment_id: '959747692627863443'
lifecycle_stage: active
run_id: 6b2c006b839b43cbaefb65f0ce8c6e1b
run_name: CentralizedCritic_MultiGrid-CompetativeRedBlueDoor-v3-CTDE-Red_c9ac8_00000
run_uuid: 6b2c006b839b43cbaefb65f0ce8c6e1b
source_name: ''
source_type: 4
source_version: ''
start_time: 1695837219193
status: 1
tags: []
user_id: unknown
